-- Auto-generated by wallust — DO NOT EDIT
local M = {}

M.base_30 = {
  white          = "#75F699",
  darker_black   = "#030001",
  black          = "#030001",
  black2         = "#030001",
  one_bg         = "#030001",
  one_bg2        = "#039F4E",
  one_bg3        = "#039F4E",
  grey           = "#039F4E",
  grey_fg        = "#039F4E",
  grey_fg2       = "#68E88D",
  light_grey     = "#68E88D",
  red            = "#1717DE",
  baby_pink      = "#1717DE",
  pink           = "#EC043F",
  line           = "#030001",
  green          = "#502AC1",
  vibrant_green  = "#502AC1",
  nord_blue      = "#1E7CD4",
  blue           = "#1E7CD4",
  yellow         = "#BD1C93",
  sun            = "#BD1C93",
  purple         = "#EC043F",
  dark_purple    = "#EC043F",
  teal           = "#18C052",
  orange         = "#1717DE",
  cyan           = "#18C052",
  statusline_bg  = "#030001",
  lightbg        = "#030001",
  pmenu_bg       = "#502AC1",
  folder_bg      = "#1E7CD4",
  lavender       = "#1E7CD4",
}

M.base_16 = {
  base00 = "#030001",
  base01 = "#030001",
  base02 = "#039F4E",
  base03 = "#039F4E",
  base04 = "#68E88D",
  base05 = "#75F699",
  base06 = "#75F699",
  base07 = "#75F699",
  base08 = "#1717DE",
  base09 = "#1717DE",
  base0A = "#BD1C93",
  base0B = "#502AC1",
  base0C = "#18C052",
  base0D = "#1E7CD4",
  base0E = "#EC043F",
  base0F = "#1717DE",
}

M.type = "dark"

M = require("base46").override_theme(M, "wallust")

return M
