-- Auto-generated by wallust — DO NOT EDIT
local M = {}

M.base_30 = {
  white          = "#F48589",
  darker_black   = "#000102",
  black          = "#000102",
  black2         = "#000102",
  one_bg         = "#000102",
  one_bg2        = "#9D4146",
  one_bg3        = "#9D4146",
  grey           = "#9D4146",
  grey_fg        = "#9D4146",
  grey_fg2       = "#D76E72",
  light_grey     = "#D76E72",
  red            = "#1E3B52",
  baby_pink      = "#1E3B52",
  pink           = "#7E2637",
  line           = "#000102",
  green          = "#541F2B",
  vibrant_green  = "#541F2B",
  nord_blue      = "#4F2259",
  blue           = "#4F2259",
  yellow         = "#212859",
  sun            = "#212859",
  purple         = "#7E2637",
  dark_purple    = "#7E2637",
  teal           = "#9B242D",
  orange         = "#1E3B52",
  cyan           = "#9B242D",
  statusline_bg  = "#000102",
  lightbg        = "#000102",
  pmenu_bg       = "#541F2B",
  folder_bg      = "#4F2259",
  lavender       = "#4F2259",
}

M.base_16 = {
  base00 = "#000102",
  base01 = "#000102",
  base02 = "#9D4146",
  base03 = "#9D4146",
  base04 = "#D76E72",
  base05 = "#F48589",
  base06 = "#F48589",
  base07 = "#F48589",
  base08 = "#1E3B52",
  base09 = "#1E3B52",
  base0A = "#212859",
  base0B = "#541F2B",
  base0C = "#9B242D",
  base0D = "#4F2259",
  base0E = "#7E2637",
  base0F = "#1E3B52",
}

M.type = "dark"

M = require("base46").override_theme(M, "wallust")

return M
