-- Auto-generated by wallust — DO NOT EDIT
local M = {}

M.base_30 = {
  white          = "#9A9EC4",
  darker_black   = "#010102",
  black          = "#010102",
  black2         = "#010102",
  one_bg         = "#010102",
  one_bg2        = "#55587B",
  one_bg3        = "#55587B",
  grey           = "#55587B",
  grey_fg        = "#55587B",
  grey_fg2       = "#8083A8",
  light_grey     = "#8083A8",
  red            = "#1A3148",
  baby_pink      = "#1A3148",
  pink           = "#5E561B",
  line           = "#010102",
  green          = "#4A2E1A",
  vibrant_green  = "#4A2E1A",
  nord_blue      = "#49171C",
  blue           = "#49171C",
  yellow         = "#1C4A1C",
  sun            = "#1C4A1C",
  purple         = "#5E561B",
  dark_purple    = "#5E561B",
  teal           = "#262D7B",
  orange         = "#1A3148",
  cyan           = "#262D7B",
  statusline_bg  = "#010102",
  lightbg        = "#010102",
  pmenu_bg       = "#4A2E1A",
  folder_bg      = "#49171C",
  lavender       = "#49171C",
}

M.base_16 = {
  base00 = "#010102",
  base01 = "#010102",
  base02 = "#55587B",
  base03 = "#55587B",
  base04 = "#8083A8",
  base05 = "#9A9EC4",
  base06 = "#9A9EC4",
  base07 = "#9A9EC4",
  base08 = "#1A3148",
  base09 = "#1A3148",
  base0A = "#1C4A1C",
  base0B = "#4A2E1A",
  base0C = "#262D7B",
  base0D = "#49171C",
  base0E = "#5E561B",
  base0F = "#1A3148",
}

M.type = "dark"

M = require("base46").override_theme(M, "wallust")

return M
